/*
 * PopUpWindow.java
 *
 * Created on October 24, 2008, 10:43 AM
 */
package com.infinity.billclint.gui;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author  Lahiru
 */
public class PopUpWindow extends javax.swing.JFrame {

    public static String MASTER_IP;
    public static   String PC_ID;

    /** Creates new form PopUpWindow */
    public PopUpWindow() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnExit);
        getData();
        MASTER_IP = txtIP1.getText().trim() + "." + txtIP2.getText().trim() + "." + txtIP3.getText().trim() + "." + txtIP4.getText().trim();
PC_ID=txtComputerName.getText();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        BM = new javax.swing.JLabel();
        SM = new javax.swing.JLabel();
        arr = new javax.swing.JLabel();
        btnNetInfo = new javax.swing.JButton();
        btnPing = new javax.swing.JButton();
        bunRestart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIP1 = new javax.swing.JFormattedTextField();
        txtIP2 = new javax.swing.JFormattedTextField();
        txtIP3 = new javax.swing.JFormattedTextField();
        txtIP4 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtComputerName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setTitle("Bill Printer ");
        setResizable(false);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Connectiotion"));

        BM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billclint/res/BM.png"))); // NOI18N
        BM.setIconTextGap(0);
        BM.setBounds(280, 30, 40, 70);
        jLayeredPane1.add(BM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billclint/res/SM.png"))); // NOI18N
        SM.setIconTextGap(0);
        SM.setBounds(20, 40, -1, -1);
        jLayeredPane1.add(SM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        arr.setFont(new java.awt.Font("Tahoma", 1, 14));
        arr.setForeground(new java.awt.Color(0, 153, 0));
        arr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billclint/res/busy.gif"))); // NOI18N
        arr.setIconTextGap(0);
        arr.setBounds(70, 50, 210, 30);
        jLayeredPane1.add(arr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnNetInfo.setText("Net Info");
        btnNetInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetInfoActionPerformed(evt);
            }
        });

        btnPing.setText("Ping");
        btnPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPingActionPerformed(evt);
            }
        });

        bunRestart.setText("Restart");
        bunRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bunRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bunRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(btnPing, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNetInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNetInfo)
                    .addComponent(btnPing)
                    .addComponent(bunRestart))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Statics", jPanel1);

        jLabel1.setText("Server IP");

        try {
            txtIP1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIP1.setToolTipText("<HTML>Your Main Severs IP <B><U>XXX.XXX.XXX.XXX</U></B>");
        txtIP1.setFont(new java.awt.Font("Tahoma", 1, 12));

        try {
            txtIP2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIP2.setToolTipText("<HTML>Your Main Severs IP <B><U>XXX.XXX.XXX.XXX</U></B>");
        txtIP2.setFont(new java.awt.Font("Tahoma", 1, 12));

        try {
            txtIP3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIP3.setToolTipText("<HTML>Your Main Severs IP <B><U>XXX.XXX.XXX.XXX</U></B>");
        txtIP3.setFont(new java.awt.Font("Tahoma", 1, 12));

        try {
            txtIP4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIP4.setToolTipText("<HTML>Your Main Severs IP <B><U>XXX.XXX.XXX.XXX</U></B>");
        txtIP4.setFont(new java.awt.Font("Tahoma", 1, 12));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(".");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(".");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(".");

        jLabel5.setText("Computer Name");

        txtComputerName.setToolTipText("<HTML>your Computre's ID for <B>Bill Printer</B>\nnot for Computer You can use <B>\"FrontChashiar'sComputer\"<B>ect ..");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("ReSet");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIP1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(txtIP2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtComputerName, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtComputerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnReset))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Setings", jPanel2);

        btnExit.setText("Close");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    setVisible(false);
}//GEN-LAST:event_btnExitActionPerformed

private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    getData();
}//GEN-LAST:event_btnResetActionPerformed

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    save();

}//GEN-LAST:event_btnSaveActionPerformed

private void btnNetInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetInfoActionPerformed
        try {
            Runtime.getRuntime().exec(".\\ip.bat");//GEN-LAST:event_btnNetInfoActionPerformed
//            Desktop.getDesktop().open(new File("ip.bat"));
        } catch (IOException ex) {
           ex.printStackTrace();
        }
}

private void btnPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPingActionPerformed
        try {
            String command ="ping -t "+ MASTER_IP;
           
            Runtime.getRuntime().exec(command.trim());//GEN-LAST:event_btnPingActionPerformed
        } catch (IOException ex) {
           ex.printStackTrace();
        }
}

private void bunRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bunRestartActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "System will restarted You only have\n 60 mins to save\n your Work \nYou want to Restart the System ?", "System Restart", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    if (i==JOptionPane.YES_OPTION) {
        SystemProssesHandaler.systemHook(SystemProssesHandaler.RESTART);
    }
}//GEN-LAST:event_bunRestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PopUpWindow().setVisible(true);
            }
        });
    }

    private void getData() {
        String fromHD = new MainHostHandler().getFromHD();
        String[] split = fromHD.split("#");
        String ip = split[0];
        String[] ips = ip.split("-");
        txtComputerName.setText(split[1]);

        txtIP1.setText(ips[0]);
        txtIP2.setText(ips[1]);
        txtIP3.setText(ips[2]);
        txtIP4.setText(ips[3]);

    }

    private void save() {
        String ipAddress = txtIP1.getText().trim() + "-" + txtIP2.getText().trim() + "-" + txtIP3.getText().trim() + "-" + txtIP4.getText().trim();
        String compName = txtComputerName.getText().trim();
        String a = ipAddress + "#" + compName;
        new MainHostHandler().writeToHD(a);

    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BM;
    private javax.swing.JLabel SM;
    private javax.swing.JLabel arr;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNetInfo;
    private javax.swing.JButton btnPing;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton bunRestart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtComputerName;
    private javax.swing.JFormattedTextField txtIP1;
    private javax.swing.JFormattedTextField txtIP2;
    private javax.swing.JFormattedTextField txtIP3;
    private javax.swing.JFormattedTextField txtIP4;
    // End of variables declaration//GEN-END:variables
}
