/*
 * MainWindow.java
 *
 * Created on September 1, 2008, 11:20 AM
 */
package com.infinity.billprinter.gui;

import com.infinity.billclint.gui.PopupMenu;
import com.infinity.billprinter.logic.Cal;
import com.infinity.billprinter.logic.ItemLoder;
import com.infinity.billprinter.logic.PrintBill;
import com.infinity.billprinter.logic.UseNet;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author  Lahiru
 */
public class MainWindow extends javax.swing.JFrame {

    private ItemLoder il;
    private DefaultTableModel modelTable;
    private float fttole;
    private NumberFormat nf;

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        setLocationRelativeTo(null);
        modelTable = (DefaultTableModel) tblItems.getModel();
        new Thread(new Runnable() {

            public void run() {
                il = new ItemLoder();
                cmbItems.setModel(new DefaultComboBoxModel(il.forCombo()));
            }
        }).start();
        setForNewBill();
        nf = NumberFormat.getCurrencyInstance();
        new Thread(time).start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbItems = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtQut = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtTotal = new javax.swing.JFormattedTextField();
        txtPayment = new javax.swing.JFormattedTextField();
        txtBalance = new javax.swing.JFormattedTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        billMenuItem = new javax.swing.JMenuItem();
        printMenuItem = new javax.swing.JMenuItem();
        checkMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        itemEditMenuItem = new javax.swing.JMenuItem();
        hfMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        useNetMenuItem = new javax.swing.JCheckBoxMenuItem();
        billsMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill Printer");
        setIconImage(Toolkit.getDefaultToolkit().getImage("./bill.png"));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "qut", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItems.getTableHeader().setReorderingAllowed(false);
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
        });
        tblItems.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblItemsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblItems);

        jLabel1.setText("Item");

        cmbItems.setEditable(true);
        cmbItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemsActionPerformed(evt);
            }
        });
        cmbItems.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbItemsKeyReleased(evt);
            }
        });

        jLabel2.setText("Amount");

        txtQut.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtQut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQutKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQutKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(txtQut, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(cmbItems, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        AutoCompleteDecorator.decorate(cmbItems);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 70, 213), 1, true), "Bill"));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblDate.setText("yy\\mm\\dd");

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblTime.setText("HH:mm:ss");

        lblID.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblID.setText("(empty)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        txtPayment.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        txtPayment.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaymentKeyReleased(evt);
            }
        });

        txtBalance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Total");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Payment");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Balance");

        fileMenu.setText("File");

        billMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        billMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billprinter/res/bill.png"))); // NOI18N
        billMenuItem.setText("Bill");
        billMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(billMenuItem);

        printMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        printMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billprinter/res/print_icon.png"))); // NOI18N
        printMenuItem.setText("Print");
        printMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(printMenuItem);

        checkMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        checkMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billprinter/res/check.png"))); // NOI18N
        checkMenuItem.setText("Check");
        checkMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(checkMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billprinter/res/Close.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        mainMenuBar.add(fileMenu);

        editMenu.setText("Edit");
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        itemEditMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billprinter/res/storage.png"))); // NOI18N
        itemEditMenuItem.setText("Item Editer ...");
        itemEditMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(itemEditMenuItem);

        hfMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billprinter/res/aboutinfo.png"))); // NOI18N
        hfMenuItem.setText("Heder/footer");
        hfMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hfMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(hfMenuItem);
        editMenu.add(jSeparator1);

        useNetMenuItem.setSelected(true);
        useNetMenuItem.setText("Use Network");
        useNetMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billprinter/res/computers.png"))); // NOI18N
        useNetMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useNetMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(useNetMenuItem);

        billsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billprinter/res/AA.png"))); // NOI18N
        billsMenuItem.setText("Resant Bills");
        billsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(billsMenuItem);

        mainMenuBar.add(editMenu);

        helpMenu.setText("Help");
        helpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuActionPerformed(evt);
            }
        });

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/infinity/billprinter/res/abnfo.png"))); // NOI18N
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        mainMenuBar.add(helpMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPayment, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void billMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billMenuItemActionPerformed
    setForNewBill();
}//GEN-LAST:event_billMenuItemActionPerformed

private void cmbItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemsActionPerformed

    if (evt.getActionCommand().equalsIgnoreCase("comboBoxEdited")) {
       txtQut.requestFocusInWindow();
    }
}//GEN-LAST:event_cmbItemsActionPerformed

private void txtQutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQutKeyReleased

    try {
        Vector<Float> v = il.forVal();
        int id = cmbItems.getSelectedIndex();
        String name = cmbItems.getSelectedItem().toString();
        int amount = Integer.parseInt(txtQut.getText().trim());
        
        if (evt.getKeyCode() == 10) {

            Object[] tableLine = Cal.tableLine(name, v, amount, id);
            modelTable.addRow(tableLine);
            setTotel();
            cmbItems.requestFocusInWindow();
            txtQut.setText(null);
            
        }else if(evt.getKeyCode() == 16){
            Object[] tableLine = Cal.tableLineSh(name, v, amount, id);
            modelTable.addRow(tableLine);
            setTotel();
            cmbItems.requestFocusInWindow();
            txtQut.setText(null);
        }else if(evt.getKeyCode() == 17){
        Object[] tableLine = Cal.tableLineCt(name, v, amount, id);
            modelTable.addRow(tableLine);
            setTotel();
            cmbItems.requestFocusInWindow();
            txtQut.setText(null);
        }
        
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Enter a number " + ex);
        txtQut.setText(null);
        txtQut.requestFocusInWindow();
    }
    
}//GEN-LAST:event_txtQutKeyReleased

private void checkMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMenuItemActionPerformed
    setTotel();
}//GEN-LAST:event_checkMenuItemActionPerformed

private void txtPaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentKeyReleased
    if (evt.getKeyCode() == 10) {
        try {
            float pay = Float.parseFloat(txtPayment.getText().trim());
            float balance = pay - fttole;
            txtBalance.setText(nf.format(balance));
            txtPayment.setText(nf.format(pay));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Enter a number " + ex);
            txtPayment.setText(null);
            txtPayment.requestFocusInWindow();
        }
    }
}//GEN-LAST:event_txtPaymentKeyReleased

private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
    print();
}//GEN-LAST:event_btnPrintActionPerformed

private void printMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMenuItemActionPerformed
    print();
}//GEN-LAST:event_printMenuItemActionPerformed

private void itemEditMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditMenuItemActionPerformed
new ItemListEditer(this, false).setVisible(true);
}//GEN-LAST:event_itemEditMenuItemActionPerformed

private void billsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsMenuItemActionPerformed
new BillList(this, false).setVisible(true);
}//GEN-LAST:event_billsMenuItemActionPerformed

private void tblItemsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblItemsKeyReleased
         if (evt.getKeyCode()==127) {
        modelTable.removeRow( tblItems.getSelectedRow());
        cmbItems.requestFocusInWindow();
    }
}//GEN-LAST:event_tblItemsKeyReleased

private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked
if (evt.getClickCount()==2) {
        modelTable.removeRow( tblItems.getSelectedRow());
        cmbItems.requestFocusInWindow();
    }
}//GEN-LAST:event_tblItemsMouseClicked

private void helpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuActionPerformed
    //humm :?
}//GEN-LAST:event_helpMenuActionPerformed

private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
new Help(this, false).setVisible(true);
}//GEN-LAST:event_aboutMenuItemActionPerformed

private void cmbItemsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbItemsKeyReleased
// humm :?
}//GEN-LAST:event_cmbItemsKeyReleased

private void txtQutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQutKeyTyped
// humm :?
}//GEN-LAST:event_txtQutKeyTyped

private void txtQutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQutKeyPressed

    
}//GEN-LAST:event_txtQutKeyPressed

private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
// :?
}//GEN-LAST:event_editMenuActionPerformed

private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
System.exit(0);
}//GEN-LAST:event_exitMenuItemActionPerformed

private void hfMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hfMenuItemActionPerformed
new HederFotterEditer(this, false).setVisible(true);
}//GEN-LAST:event_hfMenuItemActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
checkNetStatus();
}//GEN-LAST:event_formWindowOpened

private void useNetMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useNetMenuItemActionPerformed
        try {
            new UseNet().writeHD(useNetMenuItem.isSelected());
            Thread.sleep(100);
            checkNetStatus();//GEN-LAST:event_useNetMenuItemActionPerformed
        } catch (InterruptedException ex) {
           
        }
}



    private void setForNewBill() {
        for (int i = 0; i < tblItems.getRowCount();) {
            modelTable.removeRow(0);
        }
        Date d = new Date();
        DateFormat df1 = DateFormat.getDateInstance(DateFormat.MEDIUM);
        lblDate.setText(df1.format(d));
        lblID.setText("Bill:" + lblTime.getText().concat("@" + lblDate.getText()));
        txtBalance.setText(null);
        txtPayment.setText(null);
        txtQut.setText(null);
        txtTotal.setText(null);
        cmbItems.requestFocusInWindow();
    }

    private void setTotel() {
        try {
            int rowCount = tblItems.getRowCount();
            fttole = 0f;
            for (int i = 0; i < rowCount; i++) {

//                fttole = fttole + Float.valueOf(String.valueOf(tblItems.getValueAt(i, 2)).substring(1));
             fttole = fttole +nf.parse(tblItems.getValueAt(i, 2).toString()).floatValue();   
                
                
 
            }

            txtTotal.setText(nf.format(fttole));
            txtPayment.requestFocusInWindow();
        } catch (ParseException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Enter a number " + ex);
        }
    }

    private void print() {
        modelTable = (DefaultTableModel) tblItems.getModel();
        String text = lblDate.getText();
        String[] s = text.split(" ");
        final MiniProgress f = new MiniProgress(null, true);
        String[] data = new String[6];
        final Vector v = modelTable.getDataVector();
        data[0] = s[0].trim()+s[1].trim()+s[1].trim()+String.valueOf(System.currentTimeMillis()).trim();
        data[1] = lblDate.getText().trim();
        data[2] = lblTime.getText().trim();
        data[3] = txtTotal.getText().trim();
        data[4] = txtPayment.getText().trim();
        data[5] = txtBalance.getText().trim();
        final String[] d = data;
        
        Thread t2 = new Thread(new Runnable() {

            public void run() {
                new PrintBill().printBill(d, v, f);
               setForNewBill();
            }
        });
        t2.start();


    }
    
    private Runnable time=new Runnable() {

        public void run() {
            while (true) {                
                try {
                    Date d = new Date();
                    DateFormat time = DateFormat.getTimeInstance(DateFormat.MEDIUM);
                    lblTime.setText(time.format(d));
                    Thread.sleep(10);
                } catch (InterruptedException ex) {
                     }
            }
        }
    };
    
    private void checkNetStatus(){
    useNetMenuItem.setSelected(new UseNet().getFormHD());
        if (useNetMenuItem.isSelected()) {
            new PopupMenu().showIcon();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem billMenuItem;
    private javax.swing.JMenuItem billsMenuItem;
    private javax.swing.JButton btnPrint;
    private javax.swing.JMenuItem checkMenuItem;
    private javax.swing.JComboBox cmbItems;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem hfMenuItem;
    private javax.swing.JMenuItem itemEditMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem printMenuItem;
    private javax.swing.JTable tblItems;
    private javax.swing.JFormattedTextField txtBalance;
    private javax.swing.JFormattedTextField txtPayment;
    private javax.swing.JTextField txtQut;
    private javax.swing.JFormattedTextField txtTotal;
    private javax.swing.JCheckBoxMenuItem useNetMenuItem;
    // End of variables declaration//GEN-END:variables
}
